# Generated by Django 4.2 on 2024-12-01 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts/"),
        ),
    ]
