# Generated by Django 4.2 on 2024-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="post.category"),
        ),
    ]
