# Generated by Django 4.2 on 2024-12-03 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0011_alter_post_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
    ]
