# Generated by Django 4.2 on 2024-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0012_remove_category_posts_remove_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(to="post.post"),
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="post.category"),
        ),
    ]
