# Generated by Django 4.2 on 2024-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0013_category_posts_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
    ]
