# Generated by Django 4.2 on 2024-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0014_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=200),
        ),
    ]
