# Generated by Django 4.2 on 2024-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0015_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
    ]
