# Generated by Django 4.2 on 2024-12-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_alter_subscription_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
