# Generated by Django 4.2 on 2024-12-04 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_expire_time_alter_user_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
