# Generated by Django 4.2 on 2024-12-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0004_remove_subscription_users"),
        ("user", "0008_remove_user_subscription_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="subscription.subscription",
            ),
        ),
    ]
